name: Bug report
description: Report an issue with react-native-unistyles.
labels: 'Needs review'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

         Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         -  Issues tab: https://github.com/jpudysz/react-native-unistyles/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
         -  Closed issues tab: https://github.com/jpudysz/react-native-unistyles/issues?q=is%3Aissue+is%3Aclosed
         -  Discussions tab: https://github.com/jpudysz/react-native-unistyles/discussions
  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise and descriptive explanation of what the bug is. Include screenshots or a video if needed by drag and dropping them to the box below.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Snack or a link to a repository (optional)
      description: |
        Please provide a Snack (https://snack.expo.io/) or a link to a repository on GitHub under your username that reproduces the issue.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve.
        Issues without a reproduction are likely to stale.
      placeholder: Link to a Snack or a GitHub repository

  - type: input
    id: unistyles-version
    attributes:
      label: Unistyles version
      description: What version of react-native-unistyles are you using?
      placeholder: 2.0.0
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: What version of react-native are you using?
      placeholder: 0.73.0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platform your application is running on?
      multiple: true
      options:
        - Android
        - iOS
        - React Native Web
        - SSR
        - React Native Windows
    validations:
      required: true
