name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        uses: oven-sh/setup-bun@v1
        with:
          fetch-depth: 0

      - name: Install
        uses: bun install

      - name: Lint files
        run: bun run lint

      - name: Type check files
        run: bun run tsc

      - name: Run tests
        run: bun run test
